[package]
name = "sprite-splitter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sprite-splitter"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
photon-rs = "0.3.2"
